# Use the official PostgreSQL image from the Docker Hub
FROM postgres:14

# Copy the initialization script into the Docker image
COPY init.sql /docker-entrypoint-initdb.d/

# Expose the PostgreSQL port
EXPOSE 5432

