# Use the official Node.js image as the base image
FROM node:18

# Create and set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY nest-postgres-backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY nest-postgres-backend/ .

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["npm", "run", "start:dev"]

