apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjssvc
  template:
    metadata:
      labels:
        app: nestjssvc
    spec:
      containers:
      - name: nestjs
        image: cloudservos2607/nest-backend:v1
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: postgressvc
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          value: myuser
        - name: DATABASE_PASSWORD
          value: mypassword
        - name: DATABASE_NAME
          value: myapp
---
apiVersion: v1
kind: Service
metadata:
  name: nestjssvc
spec:
  selector:
    app: nestjssvc
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP

